# Enable flake8-bugbear (`B`) rules.
select = ["ALL"]
ignore = [
      "D203",
      "D212",
      "ANN101",
      "ANN102",
]
line-length = 124
target-version = "py39"

[per-file-ignores]
"**/migrations/*.py" = [
      "RUF012",
      "D101",
]
"**/manage.py" = [
      "INP001",
]
"**/*.pyi" = [
      "FBT001",
      "PLR0913",
]
"**/examples/*.py" = [
      "S101",
]
