from typing_extensions import override

def jit_mixin(obj: object, mixin: object) -> object: ...
def jit_mixin_type(base: object, *mixins: object) -> object: ...

class JITMixin:
    @override
    def __reduce__(self) -> tuple[object, ...]: ...
