"""Generated by Django 5.2.4 on 2025-08-01 09:39."""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("published_date", models.DateField(auto_now_add=True)),
                ("nb_line", models.IntegerField(default=1)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="myapp.author"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.region",
                    ),
                ),
            ],
            options={
                "db_table": "region",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "region",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="myapp.region"),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
    ]
